openapi: 3.0.1
info:
  title: Client List Coding Challenge
  description: This is the API for the Client list.
  version: 1.0-oas3
servers:
  - url: http://localhost:3000
paths:
  /providers/changeName:
    put:
      description: Modify the name of a provider
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                currentProviderName:
                  type: string
                newProviderName:
                  type: string
            examples:
              "0":
                value: |-
                  {
                    "currentProviderName": "Bagheera",
                    "newProviderName": "Baloo"
                  }
      responses:
        "200":
          description: Success
          content:
            text/html; charset=utf-8:
              schema:
                type: string
              examples:
                "0":
                  value: Name has been changed
      servers:
        - url: http://localhost:3000
    servers:
      - url: http://localhost:3000
  /providers/deleteProvider:
    post:
      description: Deletes the provider corresponding to the providerId that is passed.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                providerId:
                  type: string
            examples:
              "0":
                value: |-
                  {
                     "providerId": "61589d278033e3e4fe9465cc"
                  }
      responses:
        "200":
          description: Returns confirmation of deletion
          content:
            text/html; charset=utf-8:
              schema:
                type: string
              examples:
                "0":
                  value: |-
                    Client deleted
      servers:
        - url: http://localhost:3000
    servers:
      - url: http://localhost:3000
  /all:
    get:
      description: Get all clients and providers
      parameters:
        - in: query
          name: populated
          schema:
            type: string
          description: >-
            This will get all the clients and all the providers. The client's provider array will be populated with the provider's id and not the provider itself.
      responses:
        "200":
          description: >-
            Gets an object with a clients key and a providers key. The values of
            those keys is an array of all the clients and all the providers
            respectively.
          content:
            application/json; charset=utf-8:
              schema:
                type: object
              examples:
                "0":
                  value: |-
                    {
                      "clients": [
                          {
                              "_id": "614a3d83af489f20baa19068",
                              "name": "Test1",
                              "email": "test1@krfs.com",
                              "phone": 3050005555,
                              "providers": [
                                  "614a3d83af489f20baa19070"
                              ]
                          },
                          {
                              "_id": "614a3d83af489f20baa19069",
                              "name": "Kriea",
                              "email": "Sith@goodgirl.com",
                              "phone": 7777777777,
                              "providers": [
                                  "614a3d83af489f20baa1906e"
                              ]
                          },
                          {
                              "_id": "614cc26e291c1df0562d6120",
                              "name": "Sharmane",
                              "email": "this@that.com",
                              "phone": 5489770987,
                              "providers": [
                                  "614a3d83af489f20baa19072",
                                  "614ba218c8ea35cc2a2c8adf"
                              ]
                          }
                      ],
                      "providers": [
                          {
                              "_id": "614a3d83af489f20baa1906e",
                              "name": "Provider1"
                          },
                          {
                              "_id": "614a3d83af489f20baa1906f",
                              "name": "Provider2"
                          },
                          {
                              "_id": "614a3d83af489f20baa19070",
                              "name": "Provider3"
                          },
                          {
                              "_id": "614a3d83af489f20baa19071",
                              "name": "Provider4"
                          },
                          {
                              "_id": "614a3d83af489f20baa19072",
                              "name": "Provider5"
                          },
                          {
                              "_id": "614ba218c8ea35cc2a2c8adf",
                              "name": "What does it matter?"
                          },
                          {
                              "_id": "614ba318c8ea35cc2a2c8ae1",
                              "name": "Dark Wing Duck!"
                          },
                          {
                              "_id": "614ba577cfd01ff4f5107649",
                              "name": "Bagheera"
                          },
                          {
                              "_id": "614cc7e3ddc7a671a714edbd",
                              "name": "RainDrops"
                          }
                      ]
                    }
      servers:
        - url: http://localhost:3000
    servers:
      - url: http://localhost:3000
  /clients/createClient:
    post:
      description: Creates a new client
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: number
                name:
                  type: string
                email:
                  type: string
                providers:
                  type: array
                  items:
                    type: string
            examples:
              "0":
                value: |-
                  {
                    "name": "Darth Revan",
                    "email": "darksider@empire.com",
                    "phone": 80074845673,
                    "providers": ["614cc7e3ddc7a671a714edbd", "614ba577cfd01ff4f5107649"]

                  }
      responses:
        "200":
          description: Confirms client creation
          content:
            text/html; charset=utf-8:
              schema:
                type: string
              examples:
                "0":
                  value: Client created
      servers:
        - url: http://localhost:3000
    servers:
      - url: http://localhost:3000
  /clients/modifyClient:
    put:
      description: Modifies an existing client.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                clientId:
                  type: string
                modifiedClient:
                  type: object
                  properties:
                    phone:
                      type: number
                    name:
                      type: string
                    email:
                      type: string
                    providers:
                      type: array
                      items:
                        type: string
            examples:
              "0":
                value: |-
                  {
                    "clientId": "614cc26e291c1df0562d6120",
                    "modifiedClient": {
                        "name": "The Outcast",
                        "email": "woundedforce@jedi.com",
                        "phone": 80053346483,
                        "providers": ["614ba577cfd01ff4f5107649", "614ba318c8ea35cc2a2c8ae1"]
                    }
                  }
      responses:
        "200":
          description: Confirms modification of the client
          content:
            text/html; charset=utf-8:
              schema:
                type: string
              examples:
                "0":
                  value: Client modified
      servers:
        - url: http://localhost:3000
    servers:
      - url: http://localhost:3000
  /clients/deleteClient:
    post:
      description: This deletes a client.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                clientId:
                  type: string
            examples:
              "0":
                value: |-
                  {
                    "clientId": "614a3d83af489f20baa19068"
                  }
      responses:
        "200":
          description: Confirms deletion of the client
          content:
            text/html; charset=utf-8:
              schema:
                type: string
              examples:
                "0":
                  value: Client deleted
      servers:
        - url: http://localhost:3000
    servers:
      - url: http://localhost:3000
  /providers/createNewProvider:
    post:
      description: Creates a new provider
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
            examples:
              "0":
                value: |-
                  {
                    "name": "RainDrops"
                  }
      responses:
        "200":
          description: Confirms creation of provider
          content:
            text/html; charset=utf-8:
              schema:
                type: string
              examples:
                "0":
                  value: The provider {providerName} was created
      servers:
        - url: http://localhost:3000
    servers:
      - url: http://localhost:3000
