swagger: "2.0"
info:
  version: "1.0"
  title: ClientListApi
  description: This is the API for my technical challenge
paths: {}
# Added by API Auto Mocking Plugin
host: localhost:3000
basePath: /
schemes:
  - https
definitions:
  Model:
    type: object
    properties:
      id:
        type: integer
        format: int64
